### ISSUE TITLE
migrate javascript codebase to typescript

### ISSUE THREAD

**Issue by devblin** [devblin/davatar#13]
**Is your feature request related to a problem? Please describe.**
Currently, the library is implemented in javascript, we just need to update the codebase to typescript one.

**Comment by ahmedheltaher** [comment]
Can You Assign me on this. I Guess I Can Help

**Comment by devblin** [comment]
@ahmedheltaher Sure.

**Comment by devblin** [comment]
@ahmedheltaher please create a new branch from main `update/typescript`.

**Comment by ahmedheltaher** [comment]
Ok i will be working on it.
